routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin/home', [HomeController::class, 'adminhome'])->name('admin.home')->middleware('is_admin');
// Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('welcome', WelcomeController::class);
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/bukumedia', [App\Http\Controllers\WelcomeController::class, 'bukumedia'])->name('bukumedia');
Route::get('/profil', [App\Http\Controllers\WelcomeController::class, 'profil'])->name('profil');
Route::get('/pengunjung', [App\Http\Controllers\WelcomeController::class, 'pengunjung'])->name('pengunjung');

Route::get('/bukusearch', ['uses' => 'WelcomeController@bukusearch', 'as' => 'welcome.bukusearch']);

Route::resource('bukutamu', BukuTamuController::class)->middleware('is_admin');

Route::resource('admin', AdminController::class)->middleware('is_admin');
Route::get('/admprofil', [App\Http\Controllers\AdminController::class, 'profil'])->name('profil')->middleware('is_admin');

Route::resource('buku', BukuController::class)->middleware('is_admin');

Route::resource('anggota', AnggotaController::class)->middleware('is_admin');

Route::resource('transaksi', TransaksiController::class)->middleware('is_admin');

Route::resource('laporan', LaporanController::class)->middleware('is_admin');

Route::resource('credits', WelcomeController::class);

Auth::routes([
    'register' => false // Register Routes...
]);

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    use HasFactory;

    protected $table = 'trs_daftar';

    protected $fillable = [
        'id',
        'id_buku',
        'id_anggota',
        'tgl_pinjam',
        'tgl_kembali',
        'status',
        'ket',
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TransaksiController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksi = Transaksi::all();
        return view('transaksi.index', compact('transaksi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaksi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'cover'     => 'required|cover|mimes:png,jpg,jpeg',
        //     'lokasi'     => 'required',
        //     'content'   => 'required'
        // ]);

        $transaksi = Transaksi::create([
            'id_buku'   => $request->id_buku,
            'id_anggota'   => $request->id_anggota,
            'tgl_pinjam'   => $request->tgl_pinjam,
            'tgl_kembali'   => $request->tgl_kembali,
            'status'   => $request->status,
            'ket'   => $request->ket
        ]);

        if ($transaksi) {
            //redirect dengan pesan sukses
            return redirect()->route('transaksi.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('transaksi.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaksi $transaksi)
    {
        return view('transaksi.edit', compact('transaksi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaksi $transaksi)
    {
        // $this->validate($request, [
        //     'title'     => 'required',
        //     'content'   => 'required'
        // ]);

        //get data Blog by ID
        $transaksi = Transaksi::findOrFail($transaksi->id);

        $transaksi->update([
            'id_buku'   => $request->id_buku,
            'id_anggota'   => $request->id_anggota,
            'tgl_pinjam'   => $request->tgl_pinjam,
            'tgl_kembali'   => $request->tgl_kembali,
            'status'   => $request->status,
            'ket'   => $request->ket
        ]);


        if ($transaksi) {
            //redirect dengan pesan sukses
            return redirect()->route('transaksi.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('transaksi.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaksi = Transaksi::findOrFail($id);
        Storage::disk('local')->delete('public/cover/' . $transaksi->cover);
        $transaksi->delete();

        if ($transaksi) {
            //redirect dengan pesan sukses
            return redirect()->route('transaksi.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('transaksi.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/transaksi/create.blade.php
@extends('layout/main')

@section('title', 'TAMBAH Transaksi')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('transaksi.store') }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ID Transaksi </label>
                        <div class="col-sm-6">
                            <input type="text" name="id_buku" class="form-control" title="" placeholder="" value="{{ old('id_buku') }}" />
                        </div>
                        @error('id_buku')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ID Anggota </label>
                        <div class="col-sm-6">
                            <input type="text" name="id_anggota" class="form-control" title="" placeholder="" value="{{ old('id_anggota') }}" />
                        </div>
                        @error('id_anggota')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Pinjam </label>
                        <div class="col-sm-6">
                            <input type="date" name="tgl_pinjam" title="" class="form-control" placeholder="" value="{{ old('tgl_pinjam') }}" />
                        </div>
                        @error('tgl_pinjam')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Kembali </label>
                        <div class="col-sm-6">
                            <input type="date" name="tgl_kembali" title="" class="form-control" placeholder="" value="{{ old('tgl_kembali') }}" />
                        </div>
                        @error('tgl_kembali')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Status </label>
                        <div class="col-sm-6">
                            <input type="text" name="status" title="" class="form-control" placeholder="" value="{{ old('status') }}" />
                        </div>
                        @error('status')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Keterangan </label>
                        <div class="col-sm-6">
                            <input type="description" name="ket" title="" class="form-control" placeholder="" value="{{ old('ket') }}" />
                        </div>
                        @error('ket')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <button type="reset" class="btn btn-default">Bersihkan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/transaksi/edit.blade.php
@extends('layout/main')

@section('title', 'EDIT Transaksi')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('transaksi.update', $transaksi->id) }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            @method('PUT')
            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ID Buku </label>
                        <div class="col-sm-6">
                            <input type="text" name="id_buku" class="form-control" title="" placeholder="" value="{{ old('id_buku', $transaksi->id_buku) }}" />
                        </div>
                        @error('id_buku')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ID Anggota </label>
                        <div class="col-sm-6">
                            <input type="text" name="id_anggota" class="form-control" title="" placeholder="" value="{{ old('id_anggota', $transaksi->id_anggota) }}" />
                        </div>
                        @error('id_anggota')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Pinjam </label>
                        <div class="col-sm-6">
                            <input type="text" name="tgl_pinjam" title="" class="form-control" placeholder="" value="{{ old('tgl_pinjam', $transaksi->tgl_pinjam) }}" />
                        </div>
                        @error('tgl_pinjam')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Kembali </label>
                        <div class="col-sm-6">
                            <input type="text" name="tgl_kembali" title="" class="form-control" placeholder="" value="{{ old('tgl_kembali', $transaksi->tgl_kembali) }}" />
                        </div>
                        @error('tgl_kembali')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Status </label>
                        <div class="col-sm-6">
                            <input type="text" name="status" title="" class="form-control" placeholder="" value="{{ old('status', $transaksi->status) }}" />
                        </div>
                        @error('status')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Keterangan </label>
                        <div class="col-sm-6">
                            <textarea type="description" name="ket" rows="5" title="" class="form-control" placeholder="" value="">{{ old('ket', $transaksi->ket) }}</textarea>
                        </div>
                        @error('ket')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/transaksi/index.blade.php
@extends('layout/main')

@section('title', 'Daftar Transaksi')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <a href="{{ route('transaksi.create') }}" class="btn btn-md btn-success mb-3">TAMBAH TANSAKSI</a>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Kode</th>
                            <th>Buku</th>
                            <th>Peminjam</th>
                            <th>Tgl Pinjam</th>
                            <th>Tgl Kembali</th>
                            <th>Status</th>
                            <th>Keterangan</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i=1 @endphp
                        @forelse ($transaksi as $transaksis)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $transaksis->id }}</td>
                            <td>{{ $transaksis->id_buku }}</td>
                            <td>{{ $transaksis->id_anggota }}</td>
                            <td>{{ $transaksis->tgl_pinjam }}</td>
                            <td>{{ $transaksis->tgl_kembali }}</td>
                            <td>{{ $transaksis->status }}</td>
                            <td>{{ $transaksis->ket }}</td>
                            <td class="actions-hover actions-fade">
                                <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('transaksi.destroy', $transaksis->id) }}" method="POST">
                                    <a href="{{ route('transaksi.edit', $transaksis->id) }}" class="fa fa-pencil"></a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="fa fa-trash-o"></button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <div class="alert alert-danger">
                            Data transaksi belum Tersedia.
                        </div>
                        @endforelse
                    </tbody>
            </div>
        </section>
    </div>
</div>

<!-- end: page -->
@endsection