routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin/home', [HomeController::class, 'adminhome'])->name('admin.home')->middleware('is_admin');
// Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('welcome', WelcomeController::class);
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/bukumedia', [App\Http\Controllers\WelcomeController::class, 'bukumedia'])->name('bukumedia');
Route::get('/profil', [App\Http\Controllers\WelcomeController::class, 'profil'])->name('profil');
Route::get('/pengunjung', [App\Http\Controllers\WelcomeController::class, 'pengunjung'])->name('pengunjung');

Route::get('/bukusearch', ['uses' => 'WelcomeController@bukusearch', 'as' => 'welcome.bukusearch']);

Route::resource('bukutamu', BukuTamuController::class)->middleware('is_admin');

Route::resource('admin', AdminController::class)->middleware('is_admin');
Route::get('/admprofil', [App\Http\Controllers\AdminController::class, 'profil'])->name('profil')->middleware('is_admin');

Route::resource('buku', BukuController::class)->middleware('is_admin');

Route::resource('anggota', AnggotaController::class)->middleware('is_admin');

Route::resource('transaksi', TransaksiController::class)->middleware('is_admin');

Route::resource('laporan', LaporanController::class)->middleware('is_admin');

Route::resource('credits', WelcomeController::class);

Auth::routes([
    'register' => false // Register Routes...
]);

app/Models/BukuTamu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BukuTamu extends Model
{
    use HasFactory;

    protected $table = 'bukutamu';

    protected $fillable = [
        'nim',
        'nama',
        'kelas',
        'prodi',
        'created_at'
    ];
}

app/Http/Controllers/BukuTamuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// use Illuminate\Support\Facades\DB;
use App\Models\Profil;
use App\Models\BukuTamu;

class BukuTamuController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bukutamu = BukuTamu::all();
        return view('bukutamu.index', compact('bukutamu'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bukutamu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $bukutamu = BukuTamu::create([
            'nim'   => $request->nim,
            'nama'   => $request->nama,
            'kelas'   => $request->kelas,
            'prodi'   => $request->prodi
        ]);

        if ($bukutamu) {
            //redirect dengan pesan sukses
            return redirect()->route('bukutamu.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('bukutamu.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(BukuTamu $bukutamu)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BukuTamu $bukutamu)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bukutamu = BukuTamu::findOrFail($id);
        $bukutamu->delete();

        if ($bukutamu) {
            //redirect dengan pesan sukses
            return redirect()->route('bukutamu.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('bukutamu.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/bukutamu/create.blade.php
@extends('layout/main')

@section('title', 'TAMBAH PENGUNJUNG')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('bukutamu.store') }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">NIM </label>
                        <div class="col-sm-6">
                            <input type="text" name="nim" class="form-control" title="" placeholder="" value="{{ old('nim') }}" />
                        </div>
                        @error('nim')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Nama </label>
                        <div class="col-sm-6">
                            <input type="text" name="nama" class="form-control" title="" placeholder="" value="{{ old('nama') }}" />
                        </div>
                        @error('nama')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Kelas </label>
                        <div class="col-sm-6">
                            <input type="text" name="kelas" class="form-control" title="" placeholder="" value="{{ old('kelas') }}" />
                        </div>
                        @error('kelas')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Prodi </label>
                        <div class="col-sm-6">
                            <input type="text" name="prodi" title="" class="form-control" placeholder="" value="{{ old('prodi') }}" />
                        </div>
                        @error('prodi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <button type="reset" class="btn btn-default">Bersihkan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/bukutamu/index.blade.php
@extends('layout/main')

@section('title', 'Daftar Buku Tamu')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <a href="{{ route('bukutamu.create') }}" class="btn btn-md btn-success mb-3">TAMBAH PENGUNJUNG</a>
                <a href="/pengunjung" target="_blank" class="btn btn-md btn-success mb-3">HALAMAN PENGUNJUNG</a>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIM</th>
                            <th>Nama</th>
                            <th>Kelas</th>
                            <th>Prodi</th>
                            <th>Waktu</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i=1 @endphp
                        @forelse ($bukutamu as $bukutamus)
                        <tr>
                            <td style='vertical-align:middle'>{{ $i++ }}</td>
                            <td style='vertical-align:middle'>{{ $bukutamus->nim }}</td>
                            <td style='vertical-align:middle'>{{ $bukutamus->nama }}</td>
                            <td style='vertical-align:middle'>{{ $bukutamus->kelas }}</td>
                            <td style='vertical-align:middle'>{{ $bukutamus->prodi }}</td>
                            <td style='vertical-align:middle'>{{ $bukutamus->created_at }}</td>
                            <td class="actions-hover actions-fade">
                                <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('bukutamu.destroy', $bukutamus->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="fa fa-trash-o"></button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <div class="alert alert-danger">
                            Data Buku belum Tersedia.
                        </div>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>

<!-- end: page -->
@endsection