routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin/home', [HomeController::class, 'adminhome'])->name('admin.home')->middleware('is_admin');
// Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('welcome', WelcomeController::class);
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/bukumedia', [App\Http\Controllers\WelcomeController::class, 'bukumedia'])->name('bukumedia');
Route::get('/profil', [App\Http\Controllers\WelcomeController::class, 'profil'])->name('profil');
Route::get('/pengunjung', [App\Http\Controllers\WelcomeController::class, 'pengunjung'])->name('pengunjung');

Route::get('/bukusearch', ['uses' => 'WelcomeController@bukusearch', 'as' => 'welcome.bukusearch']);

Route::resource('bukutamu', BukuTamuController::class)->middleware('is_admin');

Route::resource('admin', AdminController::class)->middleware('is_admin');
Route::get('/admprofil', [App\Http\Controllers\AdminController::class, 'profil'])->name('profil')->middleware('is_admin');

Route::resource('buku', BukuController::class)->middleware('is_admin');

Route::resource('anggota', AnggotaController::class)->middleware('is_admin');

Route::resource('transaksi', TransaksiController::class)->middleware('is_admin');

Route::resource('laporan', LaporanController::class)->middleware('is_admin');

Route::resource('credits', WelcomeController::class);

Auth::routes([
    'register' => false // Register Routes...
]);

app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    use HasFactory;

    protected $table = 'bku_daftar';

    protected $fillable = [
        'judul',
        'isbnissn',
        'pengarang',
        'penerbit',
        'tahun',
        'kategori',
        'jenis',
        'jumlah',
        'deskripsi',
        'lokasi',
        'cover',
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Buku;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BukuController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $buku = Buku::all();
        return view('buku.index', compact('buku'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('buku.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'cover'     => 'required|cover|mimes:png,jpg,jpeg',
        //     'lokasi'     => 'required',
        //     'content'   => 'required'
        // ]);

        //upload cover
        $cover = $request->file('cover');
        $cover->storeAs('public/cover', $cover->hashName());

        $buku = Buku::create([
            'judul'   => $request->judul,
            'isbnissn'   => $request->isbnissn,
            'pengarang'   => $request->pengarang,
            'penerbit'   => $request->penerbit,
            'tahun'   => $request->tahun,
            'jumlah'   => $request->jumlah,
            'deskripsi'   => $request->deskripsi,
            'lokasi'     => $request->lokasi,
            'cover'     => $cover->hashName()
        ]);

        if ($buku) {
            //redirect dengan pesan sukses
            return redirect()->route('buku.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('buku.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Buku $buku)
    {
        return view('buku.edit', compact('buku'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Buku $buku)
    {
        // $this->validate($request, [
        //     'title'     => 'required',
        //     'content'   => 'required'
        // ]);

        //get data Blog by ID
        $buku = Buku::findOrFail($buku->id);

        if ($request->file('cover') == "") {

            $buku->update([
                'judul'   => $request->judul,
                'isbnissn'   => $request->isbnissn,
                'pengarang'   => $request->pengarang,
                'penerbit'   => $request->penerbit,
                'tahun'   => $request->tahun,
                'jumlah'   => $request->jumlah,
                'deskripsi'   => $request->deskripsi,
                'lokasi'     => $request->lokasi,
            ]);
        } else {

            //hapus old cover
            Storage::disk('local')->delete('public/cover/' . $buku->cover);

            //upload new cover
            $cover = $request->file('cover');
            $cover->storeAs('public/cover', $cover->hashName());

            $buku->update([
                'cover'     => $cover->hashName(),
                'judul'   => $request->judul,
                'isbnissn'   => $request->isbnissn,
                'pengarang'   => $request->pengarang,
                'penerbit'   => $request->penerbit,
                'tahun'   => $request->tahun,
                'jumlah'   => $request->jumlah,
                'deskripsi'   => $request->deskripsi,
                'lokasi'     => $request->lokasi
            ]);
        }

        if ($buku) {
            //redirect dengan pesan sukses
            return redirect()->route('buku.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('buku.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $buku = Buku::findOrFail($id);
        Storage::disk('local')->delete('public/cover/' . $buku->cover);
        $buku->delete();

        if ($buku) {
            //redirect dengan pesan sukses
            return redirect()->route('buku.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('buku.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/buku/create.blade.php
@extends('layout/main')

@section('title', 'TAMBAH DATA BUKU')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('buku.store') }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Judul </label>
                        <div class="col-sm-6">
                            <input type="text" name="judul" class="form-control" title="" placeholder="" value="{{ old('judul') }}" />
                        </div>
                        @error('judul')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ISBN/ISSN </label>
                        <div class="col-sm-6">
                            <input type="text" name="isbnissn" class="form-control" title="" placeholder="" value="{{ old('isbnissn') }}" />
                        </div>
                        @error('isbnissn')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Pengarang </label>
                        <div class="col-sm-6">
                            <input type="text" name="pengarang" title="" class="form-control" placeholder="" value="{{ old('pengarang') }}" />
                        </div>
                        @error('pengarang')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Penerbit </label>
                        <div class="col-sm-6">
                            <input type="text" name="penerbit" title="" class="form-control" placeholder="" value="{{ old('penerbit') }}" />
                        </div>
                        @error('penerbit')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tahun </label>
                        <div class="col-sm-6">
                            <input type="text" name="tahun" title="" class="form-control" placeholder="" value="{{ old('tahun') }}" />
                        </div>
                        @error('tahun')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Jumlah </label>
                        <div class="col-sm-6">
                            <input type="text" name="jumlah" title="" class="form-control" placeholder="" value="{{ old('jumlah') }}" />
                        </div>
                        @error('jumlah')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Deskripsi </label>
                        <div class="col-sm-6">
                            <textarea type="description" name="deskripsi" rows="5" title="" class="form-control" placeholder="" value="">{{ old('deskripsi') }}</textarea>
                        </div>
                        @error('deskripsi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Rak </label>
                        <div class="col-sm-6">
                            <input type="text" name="lokasi" title="" class="form-control" placeholder="" value="{{ old('lokasi') }}" />
                        </div>
                        @error('lokasi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Cover </label>
                        <div class="col-sm-6">
                            <input type="file" class="form-control @error('cover') is-invalid @enderror" name="cover">
                        </div>
                        @error('cover')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <button type="reset" class="btn btn-default">Bersihkan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/buku/edit.blade.php
@extends('layout/main')

@section('title', 'EDIT DATA BUKU')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('buku.update', $buku->id) }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            @method('PUT')

            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Judul </label>
                        <div class="col-sm-6">
                            <input type="text" name="judul" class="form-control" title="" placeholder="" value="{{ old('judul', $buku->judul) }}" />
                        </div>
                        @error('judul')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">ISBN/ISSN </label>
                        <div class="col-sm-6">
                            <input type="text" name="isbnissn" class="form-control" title="" placeholder="" value="{{ old('isbnissn', $buku->isbnissn) }}" />
                        </div>
                        @error('isbnissn')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Pengarang </label>
                        <div class="col-sm-6">
                            <input type="text" name="pengarang" title="" class="form-control" placeholder="" value="{{ old('pengarang', $buku->pengarang) }}" />
                        </div>
                        @error('pengarang')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Penerbit </label>
                        <div class="col-sm-6">
                            <input type="text" name="penerbit" title="" class="form-control" placeholder="" value="{{ old('penerbit', $buku->penerbit) }}" />
                        </div>
                        @error('penerbit')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tahun </label>
                        <div class="col-sm-6">
                            <input type="text" name="tahun" title="" class="form-control" placeholder="" value="{{ old('tahun', $buku->tahun) }}" />
                        </div>
                        @error('tahun')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Jumlah </label>
                        <div class="col-sm-6">
                            <input type="text" name="jumlah" title="" class="form-control" placeholder="" value="{{ old('jumlah', $buku->jumlah) }}" />
                        </div>
                        @error('jumlah')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Deskripsi </label>
                        <div class="col-sm-6">
                            <textarea type="description" name="deskripsi" rows="5" title="" class="form-control" placeholder="" value="">{{ old('deskripsi', $buku->deskripsi) }}</textarea>
                        </div>
                        @error('deskripsi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Rak </label>
                        <div class="col-sm-6">
                            <input type="text" name="lokasi" title="" class="form-control" placeholder="" value="{{ old('lokasi', $buku->lokasi) }}" />
                        </div>
                        @error('lokasi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Cover </label>
                        <div class="col-sm-6">
                            <input type="file" class="form-control @error('cover') is-invalid @enderror" name="cover">
                        </div>
                        @error('cover')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/buku/index.blade.php
@extends('layout/main')

@section('title', 'Daftar Buku')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <a href="{{ route('buku.create') }}" class="btn btn-md btn-success mb-3">TAMBAH DATA BUKU</a>
                <a href="/bukumedia" target="_blank" class="btn btn-md btn-success mb-3">HALAMAN BUKU</a>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Cover</th>
                            <th>Judul</th>
                            <th>ISBN/ISSN</th>
                            <th>Jumlah</th>
                            <th>Deskripsi</th>
                            <th>Rak</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i=1 @endphp
                        @forelse ($buku as $bukus)
                        <tr>
                            <td style='vertical-align:middle'>{{ $i++ }}</td>
                            <td style='vertical-align:middle'><img src="{{ Storage::url('public/cover/').$bukus->cover }}" class="rounded" style="width: 60px"></td>
                            <td style='vertical-align:middle'>{{ $bukus->judul }}
                                <p>{{ $bukus->pengarang }} | {{ $bukus->penerbit }} | {{ $bukus->tahun }}</p>
                            </td>
                            <td style='vertical-align:middle'>{{ $bukus->isbnissn }}</td>
                            <td style='vertical-align:middle'>{{ $bukus->jumlah }}</td>
                            <td style='vertical-align:middle'>{{ $bukus->deskripsi }}</td>
                            <td style='vertical-align:middle'>{{ $bukus->lokasi }}</td>
                            <td class="actions-hover actions-fade">
                                <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('buku.destroy', $bukus->id) }}" method="POST">
                                    <a href="{{ route('buku.edit', $bukus->id) }}" class="fa fa-pencil"></a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="fa fa-trash-o"></button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <div class="alert alert-danger">
                            Data Buku belum Tersedia.
                        </div>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>

<!-- end: page -->
@endsection