routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin/home', [HomeController::class, 'adminhome'])->name('admin.home')->middleware('is_admin');
// Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('welcome', WelcomeController::class);
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/welcome', [App\Http\Controllers\WelcomeController::class, 'index'])->name('index');
Route::get('/bukumedia', [App\Http\Controllers\WelcomeController::class, 'bukumedia'])->name('bukumedia');
Route::get('/profil', [App\Http\Controllers\WelcomeController::class, 'profil'])->name('profil');
Route::get('/pengunjung', [App\Http\Controllers\WelcomeController::class, 'pengunjung'])->name('pengunjung');

Route::get('/bukusearch', ['uses' => 'WelcomeController@bukusearch', 'as' => 'welcome.bukusearch']);

Route::resource('bukutamu', BukuTamuController::class)->middleware('is_admin');

Route::resource('admin', AdminController::class)->middleware('is_admin');
Route::get('/admprofil', [App\Http\Controllers\AdminController::class, 'profil'])->name('profil')->middleware('is_admin');

Route::resource('buku', BukuController::class)->middleware('is_admin');

Route::resource('anggota', AnggotaController::class)->middleware('is_admin');

Route::resource('transaksi', TransaksiController::class)->middleware('is_admin');

Route::resource('laporan', LaporanController::class)->middleware('is_admin');

Route::resource('credits', WelcomeController::class);

Auth::routes([
    'register' => false // Register Routes...
]);

app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;

class AnggotaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $anggota = User::all();
        return view('anggota.index', compact('anggota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('anggota.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            // 'password' => ['required', 'string', 'min:8', 'confirmed'],

            //     'foto'     => 'required|foto|mimes:png,jpg,jpeg',
            //     'lokasi'     => 'required',
            //     'content'   => 'required'
        ]);

        //upload foto
        $foto = $request->file('foto');
        $foto->storeAs('public/foto', $foto->hashName());

        $anggota = User::create([
            'name'   => $request->name,
            'nim'   => $request->nim,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'tgl_lahir'   => $request->tgl_lahir,
            'jk'   => $request->jk,
            'alamat'   => $request->alamat,
            'tlp'   => $request->tlp,
            'prodi'     => $request->prodi,
            'foto'     => $foto->hashName()
        ]);

        if ($anggota) {
            //redirect dengan pesan sukses
            return redirect()->route('anggota.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('anggota.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $anggota)
    {
        return view('anggota.edit', compact('anggota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $anggota)
    {
        // $this->validate($request, [
        //     'title'     => 'required',
        //     'content'   => 'required'
        // ]);

        //get data Blog by ID
        $anggota = User::findOrFail($anggota->id);

        if ($request->file('foto') == "") {

            $anggota->update([
                'name'   => $request->name,
                'nim'   => $request->nim,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'tgl_lahir'   => $request->tgl_lahir,
                'jk'   => $request->jk,
                'alamat'   => $request->alamat,
                'tlp'   => $request->tlp,
                'prodi'     => $request->prodi,
            ]);
        } else {

            //hapus old foto
            Storage::disk('local')->delete('public/foto/' . $anggota->foto);

            //upload new foto
            $foto = $request->file('foto');
            $foto->storeAs('public/foto', $foto->hashName());

            $anggota->update([
                'foto'     => $foto->hashName(),
                'name'   => $request->name,
                'nim'   => $request->nim,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'tgl_lahir'   => $request->tgl_lahir,
                'jk'   => $request->jk,
                'alamat'   => $request->alamat,
                'tlp'   => $request->tlp,
                'prodi'     => $request->prodi,
            ]);
        }

        if ($anggota) {
            //redirect dengan pesan sukses
            return redirect()->route('anggota.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('anggota.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $anggota = User::findOrFail($id);
        Storage::disk('local')->delete('public/foto/' . $anggota->foto);
        $anggota->delete();

        if ($anggota) {
            //redirect dengan pesan sukses
            return redirect()->route('anggota.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('anggota.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/anggota/create.blade.php
@extends('layout/main')

@section('title', 'TAMBAH ANGGOTA')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('anggota.store') }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Nama </label>
                        <div class="col-sm-6">
                            <input type="text" name="name" class="form-control" title="" placeholder="" value="{{ old('name') }}" />
                        </div>
                        @error('name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">NIM </label>
                        <div class="col-sm-6">
                            <input type="text" name="nim" class="form-control" title="" placeholder="" value="{{ old('nim') }}" />
                        </div>
                        @error('nim')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Email </label>
                        <div class="col-sm-6">
                            <input type="email" name="email" title="" class="form-control" placeholder="" value="@mhs.stmik-sumedang.ac.id {{ old('email') }}" />
                        </div>
                        @error('email')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Password </label>
                        <div class="col-sm-6">
                            <input type="password" name="password" title="" class="form-control" placeholder="" value="{{ old('password') }}" />
                        </div>
                        @error('password')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Lahir </label>
                        <div class="col-sm-6">
                            <input type="date" name="tgl_lahir" title="" class="form-control" placeholder="" value="{{ old('tgl_lahir') }}" />
                        </div>
                        @error('tgl_lahir')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Jenis Kelamin </label>
                        <div class="col-sm-6">
                            <input type="text" name="jk" title="" class="form-control" placeholder="" value="{{ old('jk') }}" />
                        </div>
                        @error('tgl_lahir')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Alamat </label>
                        <div class="col-sm-6">
                            <input type="text" name="alamat" title="" class="form-control" placeholder="" value="{{ old('alamat') }}" />
                        </div>
                        @error('alamat')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">No. HP </label>
                        <div class="col-sm-6">
                            <input type="text" name="tlp" title="" class="form-control" placeholder="" value="{{ old('tlp') }}" />
                        </div>
                        @error('tlp')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Prodi </label>
                        <div class="col-sm-6">
                            <input type="text" name="prodi" title="" class="form-control" placeholder="" value="{{ old('prodi') }}" />
                        </div>
                        @error('prodi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Foto </label>
                        <div class="col-sm-6">
                            <input type="file" class="form-control @error('foto') is-invalid @enderror" name="foto">
                        </div>
                        @error('foto')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <button type="reset" class="btn btn-default">Bersihkan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/anggota/edit.blade.php
@extends('layout/main')

@section('title', 'EDIT DATA anggota')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <form action="{{ route('anggota.update', $anggota->id) }}" method="POST" enctype="multipart/form-data" id="summary-form" class="form-horizontal">
            @csrf
            @method('PUT')

            <section class="panel">
                <div class="panel-body">
                    <div class="validation-message">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Nama </label>
                        <div class="col-sm-6">
                            <input type="text" name="name" class="form-control" title="" placeholder="" value="{{ old('name', $anggota->name) }}" />
                        </div>
                        @error('name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">NIM </label>
                        <div class="col-sm-6">
                            <input type="text" name="nim" class="form-control" title="" placeholder="" value="{{ old('nim', $anggota->nim) }}" />
                        </div>
                        @error('nim')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Email </label>
                        <div class="col-sm-6">
                            <input type="email" name="email" title="" class="form-control" placeholder="" value="{{ old('email', $anggota->email) }}" />
                        </div>
                        @error('email')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Password </label>
                        <div class="col-sm-6">
                            <input type="password" name="password" title="" class="form-control" placeholder="" value="{{ old('password', $anggota->password) }}" />
                        </div>
                        @error('password')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Tanggal Lahir </label>
                        <div class="col-sm-6">
                            <input type="date" name="tgl_lahir" title="" class="form-control" placeholder="" value="{{ old('tgl_lahir', $anggota->tgl_lahir) }}" />
                        </div>
                        @error('tgl_lahir')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Jenis Kelamin </label>
                        <div class="col-sm-6">
                            <input type="text" name="jk" title="" class="form-control" placeholder="" value="{{ old('jk', $anggota->jk) }}" />
                        </div>
                        @error('jk')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Alamat </label>
                        <div class="col-sm-6">
                            <textarea type="text" name="alamat" rows="5" title="" class="form-control" placeholder="" value="">{{ old('alamat', $anggota->alamat) }}</textarea>
                        </div>
                        @error('alamat')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">No. HP </label>
                        <div class="col-sm-6">
                            <input type="text" name="tlp" title="" class="form-control" placeholder="" value="{{ old('tlp', $anggota->tlp) }}" />
                        </div>
                        @error('tlp')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Prodi </label>
                        <div class="col-sm-6">
                            <input type="text" name="prodi" title="" class="form-control" placeholder="" value="{{ old('prodi', $anggota->prodi) }}" />
                        </div>
                        @error('prodi')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">Foto </label>
                        <div class="col-sm-6">
                            <input type="file" class="form-control @error('foto') is-invalid @enderror" name="foto">
                        </div>
                        @error('foto')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </footer>
            </section>
        </form>
    </div>
</div>

<!-- end: page -->
@endsection

resources/views/anggota/index.blade.php
@extends('layout/main')

@section('title', 'Daftar ANGGOTA')

@section('container')
<!-- start: page -->

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <a href="{{ route('anggota.create') }}" class="btn btn-md btn-success mb-3">TAMBAH ANGGOTA</a>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Foto</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Tanggal Lahir</th>
                            <th>Jenis Kelamin</th>
                            <th>Alamat</th>
                            <th>No. HP</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i=1 @endphp
                        @forelse ($anggota as $anggotas)
                        <tr>
                            <td style='vertical-align:middle'>{{ $i++ }}</td>
                            <td style='vertical-align:middle'><img src="{{ Storage::url('public/foto/').$anggotas->foto }}" class="rounded" style="width: 100px"></td>
                            <td style='vertical-align:middle'>{{ $anggotas->name }}
                                <p>{{ $anggotas->nim }} | {{ $anggotas->prodi }}</p>
                            </td>
                            <td style='vertical-align:middle'>{{ $anggotas->email }}</td>
                            <td style='vertical-align:middle'>{{ $anggotas->tgl_lahir }}</td>
                            <td style='vertical-align:middle'>{{ $anggotas->jk }}</td>
                            <td style='vertical-align:middle'>{{ $anggotas->alamat }}</td>
                            <td style='vertical-align:middle'>{{ $anggotas->tlp }}</td>
                            <td class="actions-hover actions-fade">
                                <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('anggota.destroy', $anggotas->id) }}" method="POST">
                                    <!-- <a href="{{ route('anggota.edit', $anggotas->id) }}" class="fa fa-pencil"></a> -->
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="fa fa-trash-o"></button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <div class="alert alert-danger">
                            Data anggota belum Tersedia.
                        </div>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>

<!-- end: page -->
@endsection